const PRINTS = [
    {
        "bigImage": "/build/assets/3dprints/1.jpg",
        "thumbnail": "/build/assets/3dprints/1_thumb.jpg",
        "width": 1892,
        "height": 2156
    }, {
        "bigImage": "/build/assets/3dprints/2.jpg",
        "thumbnail": "/build/assets/3dprints/2_thumb.jpg",
        "width": 1756,
        "height": 2232
    }, {
        "bigImage": "/build/assets/3dprints/3.jpg",
        "thumbnail": "/build/assets/3dprints/3_thumb.jpg",
        "width": 1816,
        "height": 2372
    }, {
        "bigImage": "/build/assets/3dprints/4.jpg",
        "thumbnail": "/build/assets/3dprints/4_thumb.jpg",
        "width": 1692,
        "height": 2216
    }, {
        "bigImage": "/build/assets/3dprints/5.jpg",
        "thumbnail": "/build/assets/3dprints/5_thumb.jpg",
        "width": 1688,
        "height": 2032
    }, {
        "bigImage": "/build/assets/3dprints/6.jpg",
        "thumbnail": "/build/assets/3dprints/6_thumb.jpg",
        "width": 1764,
        "height": 1832
    }, {
        "bigImage": "/build/assets/3dprints/7.jpg",
        "thumbnail": "/build/assets/3dprints/7_thumb.jpg",
        "width": 1680,
        "height": 2664
    }, {
        "bigImage": "/build/assets/3dprints/8.jpg",
        "thumbnail": "/build/assets/3dprints/8_thumb.jpg",
        "width": 1420,
        "height": 2392
    }, {
        "bigImage": "/build/assets/3dprints/9.jpg",
        "thumbnail": "/build/assets/3dprints/9_thumb.jpg",
        "width": 1524,
        "height": 1880
    }, {
        "bigImage": "/build/assets/3dprints/10.jpg",
        "thumbnail": "/build/assets/3dprints/10_thumb.jpg",
        "width": 1484,
        "height": 1844
    }, {
        "bigImage": "/build/assets/3dprints/11.jpg",
        "thumbnail": "/build/assets/3dprints/11_thumb.jpg",
        "width": 1704,
        "height": 2816
    }, {
        "bigImage": "/build/assets/3dprints/12.jpg",
        "thumbnail": "/build/assets/3dprints/12_thumb.jpg",
        "width": 1800,
        "height": 2392
    }, {
        "bigImage": "/build/assets/3dprints/13.jpg",
        "thumbnail": "/build/assets/3dprints/13_thumb.jpg",
        "width": 1852,
        "height": 2172
    }, {
        "bigImage": "/build/assets/3dprints/14.jpg",
        "thumbnail": "/build/assets/3dprints/14_thumb.jpg",
        "width": 1628,
        "height": 2300
    }, {
        "bigImage": "/build/assets/3dprints/15.jpg",
        "thumbnail": "/build/assets/3dprints/15_thumb.jpg",
        "width": 1468,
        "height": 2140
    }, {
        "bigImage": "/build/assets/3dprints/16.jpg",
        "thumbnail": "/build/assets/3dprints/16_thumb.jpg",
        "width": 1564,
        "height": 2104
    }, {
        "bigImage": "/build/assets/3dprints/17.jpg",
        "thumbnail": "/build/assets/3dprints/17_thumb.jpg",
        "width": 1532,
        "height": 2064
    }, {
        "bigImage": "/build/assets/3dprints/18.jpg",
        "thumbnail": "/build/assets/3dprints/18_thumb.jpg",
        "width": 1688,
        "height": 1976
    }, {
        "bigImage": "/build/assets/3dprints/19.jpg",
        "thumbnail": "/build/assets/3dprints/19_thumb.jpg",
        "width": 1508,
        "height": 2104
    }, {
        "bigImage": "/build/assets/3dprints/20.jpg",
        "thumbnail": "/build/assets/3dprints/20_thumb.jpg",
        "width": 1836,
        "height": 2308
    }, {
        "bigImage": "/build/assets/3dprints/21.jpg",
        "thumbnail": "/build/assets/3dprints/21_thumb.jpg",
        "width": 1516,
        "height": 1596
    }, {
        "bigImage": "/build/assets/3dprints/22.jpg",
        "thumbnail": "/build/assets/3dprints/22_thumb.jpg",
        "width": 1660,
        "height": 2264
    }, {
        "bigImage": "/build/assets/3dprints/23.jpg",
        "thumbnail": "/build/assets/3dprints/23_thumb.jpg",
        "width": 1456,
        "height": 2200
    }, {
        "bigImage": "/build/assets/3dprints/24.jpg",
        "thumbnail": "/build/assets/3dprints/24_thumb.jpg",
        "width": 1416,
        "height": 1996
    }, {
        "bigImage": "/build/assets/3dprints/25.jpg",
        "thumbnail": "/build/assets/3dprints/25_thumb.jpg",
        "width": 1264,
        "height": 2624
    }, {
        "bigImage": "/build/assets/3dprints/26.jpg",
        "thumbnail": "/build/assets/3dprints/26_thumb.jpg",
        "width": 1416,
        "height": 2568
    }, {
        "bigImage": "/build/assets/3dprints/27.jpg",
        "thumbnail": "/build/assets/3dprints/27_thumb.jpg",
        "width": 1340,
        "height": 2476
    }, {
        "bigImage": "/build/assets/3dprints/28.jpg",
        "thumbnail": "/build/assets/3dprints/28_thumb.jpg",
        "width": 1684,
        "height": 1828
    }, {
        "bigImage": "/build/assets/3dprints/29.jpg",
        "thumbnail": "/build/assets/3dprints/29_thumb.jpg",
        "width": 1832,
        "height": 1452
    }, {
        "bigImage": "/build/assets/3dprints/30.jpg",
        "thumbnail": "/build/assets/3dprints/30_thumb.jpg",
        "width": 1672,
        "height": 1684
    }, {
        "bigImage": "/build/assets/3dprints/31.jpg",
        "thumbnail": "/build/assets/3dprints/31_thumb.jpg",
        "width": 1644,
        "height": 2272
    }, {
        "bigImage": "/build/assets/3dprints/32.jpg",
        "thumbnail": "/build/assets/3dprints/32_thumb.jpg",
        "width": 1696,
        "height": 3660
    }, {
        "bigImage": "/build/assets/3dprints/33.jpg",
        "thumbnail": "/build/assets/3dprints/33_thumb.jpg",
        "width": 1460,
        "height": 2540
    }, {
        "bigImage": "/build/assets/3dprints/34.jpg",
        "thumbnail": "/build/assets/3dprints/34_thumb.jpg",
        "width": 1400,
        "height": 2496
    }, {
        "bigImage": "/build/assets/3dprints/35.jpg",
        "thumbnail": "/build/assets/3dprints/35_thumb.jpg",
        "width": 1924,
        "height": 2004
    }, {
        "bigImage": "/build/assets/3dprints/36.jpg",
        "thumbnail": "/build/assets/3dprints/36_thumb.jpg",
        "width": 1936,
        "height": 1628
    }, {
        "bigImage": "/build/assets/3dprints/37.jpg",
        "thumbnail": "/build/assets/3dprints/37_thumb.jpg",
        "width": 1928,
        "height": 1336
    }, {
        "bigImage": "/build/assets/3dprints/39.jpg",
        "thumbnail": "/build/assets/3dprints/39_thumb.jpg",
        "width": 1940,
        "height": 3140
    }, {
        "thumbnail": "/build/assets/3dprints/39_thumb.jpg",
        "video": "/build/assets/3dprints/40.mp4"
    }
];

export {PRINTS};
